# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Second Build
    - bash: echo $(pipelineLevelVariables)

- stage: DevDeploy
  variables:
    environment: Dev
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo Build $(environment)DeployJob
    - bash: echo $(Agent.OS)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(Build.Repository.Name)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: echo $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
# - stage: QADeploy
#   jobs:
#   - job: QAJob
#     variables: 
#       environment: QA
#     steps:
#     - bash: echo QA Job Build
#     - bash: echo $(environment) job build